// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4YwfBkdMz2JKFIpRXdcpz5dhLbHO9BII',
    appId: '1:64177655201:web:476ff16e8de805d8de8fe0',
    messagingSenderId: '64177655201',
    projectId: 'skilern-8571f',
    authDomain: 'skilern-8571f.firebaseapp.com',
    storageBucket: 'skilern-8571f.firebasestorage.app',
    measurementId: 'G-SDQLJWR4XS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBg01w9sM02pD0mI8N2kcN5v-YAW039grw',
    appId: '1:64177655201:android:68c6a94f5322118bde8fe0',
    messagingSenderId: '64177655201',
    projectId: 'skilern-8571f',
    storageBucket: 'skilern-8571f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUcNFRWlUGXy-1sqUUCBTuFpjM9IkXN4k',
    appId: '1:64177655201:ios:bc82ad4c98a34f5e4edef9',
    messagingSenderId: '64177655201',
    projectId: 'skilern-8571f',
    storageBucket: 'skilern-8571f.firebasestorage.app',
    iosBundleId: 'com.example.studentTaskBiddingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUcNFRWlUGXy-1sqUUCBTuFpjM9IkXN4k',
    appId: '1:798914252668:ios:bc82ad4c98a34f5e4edef9',
    messagingSenderId: '798914252668',
    projectId: 'skillbid-prod',
    storageBucket: 'skillbid-prod.firebasestorage.app',
    iosBundleId: 'com.example.studentTaskBiddingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4YwfBkdMz2JKFIpRXdcpz5dhLbHO9BII',
    appId: '1:64177655201:web:476ff16e8de805d8de8fe0',
    messagingSenderId: '64177655201',
    projectId: 'skilern-8571f',
    authDomain: 'skilern-8571f.firebaseapp.com',
    storageBucket: 'skilern-8571f.firebasestorage.app',
    measurementId: 'G-SDQLJWR4XS',
  );
}
